package com.raywenderlich.listmaker.ui.detail.ui.detail

import androidx.recyclerview.widget.RecyclerView
import com.raywenderlich.listmaker.databinding.ListItemViewHolderBinding

//ListItemViewHolderBinding generated by Android Studio once the layout for the ViewHolder is created
class ListItemViewHolder(val binding: ListItemViewHolderBinding) : RecyclerView.ViewHolder(binding.root) {
}