package com.raywenderlich.listmaker.ui.main

import androidx.lifecycle.ViewModelProvider
import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.recyclerview.widget.LinearLayoutManager
import com.raywenderlich.listmaker.databinding.FragmentMainBinding

class MainFragment : Fragment() {

    /* The same name as the res/layout/fragment_main.xml =>  FragmentMain + Binding
    * FragmentMainBinding object has been generated by Android Studio because ViewBinding is enabled
    * Android Studio will do this for every layout in your project, with the binding object containing properties for each View
    * */
    private lateinit var binding: FragmentMainBinding

    companion object {
        fun newInstance() = MainFragment()
    }

    private lateinit var viewModel: MainViewModel

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        viewModel = ViewModelProvider(this).get(MainViewModel::class.java)
        // TODO: Use the ViewModel
    }

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        //link to the binding
        binding = FragmentMainBinding.inflate(inflater, container, false)

        //id:lists_recyclerview; object declared in fragment_main.xml
        binding.listsRecyclerview.layoutManager = LinearLayoutManager(requireContext())//something to arrange your items in a linear format

        //to use this Adapter to acquire its data to show
        binding.listsRecyclerview.adapter = ListSelectionRecyclerViewAdapter()

        return binding.root
    }

}